services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: challenge-fambec-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
      - MSSQL_AGENT_ENABLED=false
      - MSSQL_TELEMETRY_ENABLED=false
      - MSSQL_TRACEFLAG=3226,3608,1204,1222,2528
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
    networks:
      - challenge-fambec-network

  api:
    build:
      context: .
      dockerfile: Challenge_Fambec.Server/Dockerfile.dev
    container_name: challenge-fambec-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Logging__LogLevel__Default=Warning
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__Microsoft.EntityFrameworkCore=Warning
    ports:
      - "5001:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      # Mounts your source code so the entrypoint script is found and live-reload works
      - .:/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - challenge-fambec-network
    # The command for the script to execute after the certificate check
    command: ["dotnet", "watch", "run", "--no-launch-profile"]

  client:
    build:
      context: .
      dockerfile: Challenge_Fambec.Client/Dockerfile.dev
    container_name: challenge-fambec-client
    ports:
      - "5000:80"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - challenge-fambec-network

volumes:
  sqlserver_data:

networks:
  challenge-fambec-network:
    driver: bridge
