FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Challenge_Fambec.Client/Challenge_Fambec.Client.csproj", "Challenge_Fambec.Client/"]
COPY ["Challenge_Fambec.Shared/Challenge_Fambec.Shared.csproj", "Challenge_Fambec.Shared/"]
RUN dotnet restore "Challenge_Fambec.Client/Challenge_Fambec.Client.csproj"
COPY . .
WORKDIR "/src/Challenge_Fambec.Client"
RUN dotnet build "Challenge_Fambec.Client.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Challenge_Fambec.Client.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY Challenge_Fambec.Client/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
